### Todos:
### 1. preprocess the data to make it suitable for glove embeding:
### a. remove ' from words( don't -> dont)
### b. convert all letters to lowercase ( Hoping -> hoping)
### 2. find the frequency of each emoji to see if the dataset is balanced and balance the dataset(important)

In [0]:
import csv
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torchtext
import numpy as np
import matplotlib.pyplot as plt

In [0]:
import pandas

In [0]:
def get_data():
    header = ['tweet','label']
    data_set = pandas.read_csv('cleaned_data.txt',delimiter='\t',names = header)
    return data_set

def split_tweet(tweet):
    return tweet.split()    


In [0]:
data_set = get_data()

In [7]:
glove = torchtext.vocab.GloVe(name="twitter.27B",dim=50)

# inser padding character into glove embedding, we overwrite the first element and that's okay
# because we don't use the first element in our vocab
glove.vectors[0] = torch.tensor(np.zeros(50))

.vector_cache/glove.twitter.27B.zip: 1.52GB [00:26, 57.7MB/s]                            
100%|█████████▉| 1190290/1193514 [00:35<00:00, 34480.83it/s]

In [8]:
len(data_set)

161893

In [9]:
data_set

tweet  label
0                   hoping i dont screw up this interview      0
1       i feel like a baby kangaroo stuck in its mothe...      1
2       girl ppl should be happy i even remembered her...      0
3       oh ,  the irony if misha wins the choice tv sc...      2
4                       i miss you to  ,  you so fake now      2
5                       i miss you to  ,  you so fake now      4
6                                                  i know      1
7                                      bacolod please ? !      0
8                            things can change so quickly      1
9       all me &amp ;  vic do is laugh .  .  anybody o...      1
10      do u have to remind me i was bored right after...      0
11      its ok love .  you are sweet ,  but i know you...      0
12      nainai has said bitch twice in 4 minutes and i...      0
13      louis thank you for everything you do you dese...      0
14      impractical jokers its almost always on in our...      0
15      my eyes are in pain .  cant get over the movie...      1
16                                            daydrinking      0
17                                                genitin      0
18                                         like like like      0
19                  eye need to get these brows done asap      1
20                i almost choked on my retainer just now      1
21           ms .  mendiola works miracles! shes so great      1
22      oh and parking dont even get me started on the...      2
23      oh and parking dont even get me started on the...      4
24      trying to stay my ass in the burbs but im gett...      1
25                             oh my god riley is so cute      0
26                                                why doe      0
27                i cant wait to be on the beach tomorrow      0
28        - warrior basti also will have his claws cut .       0
29      not bein selfish .  .  im only workin wit one arm      0
...                                                   ...    ...
161863                          wish i knew her last name      4
161864  lmao is it bad if my friends hit me up to tell...      0
161865             when he calls you his partner in crime      0
161866       nigga .  .  you don watch the new episode ?       5
161867  but he died cause of a car accident no one kil...      0
161868                             what we looking for ?       3
161869        all i do is share shit so that evens it out      0
161870  sister goals let stop for people say im acting...      0
161871  sister goals let stop for people say im acting...      1
161872                 is so cant wait to see him live at      1
161873                   i was chilling and i still am .       0
161874                                        tirs au but      1
161875                    yeaah im just tryin a new style      0
161876       you off earlyyyy ?  lets do something please      1
161877  thats how blew i am .  .  .  a nigga couldnt e...      4
161878  stressed is such an understatement the only th...      0
161879  stressed is such an understatement the only th...      1
161880  happy birthday to you my beautiful sk may god ...      0
161881                                             thanks      0
161882                              carebear w/ the teeth      0
161883  brooo .  its so frustrating .  theres no reaso...      1
161884                          on that note ;  goodnight      0
161885  i just realized something ive never been in a ...      3
161886  i just realized something ive never been in a ...      5
161887                            im boutta go take a nap      0
161888       closing sucked but its still been a good day      0
161889  thank god my friends love me and will listen t...      0
161890                                             blowed      0
161891                  london agent + ibs = full of shit      0
161892                  london agent + ibs = full of shit      4

[161893 rows x 2 colu

In [0]:
def data_set_to_glove_index(glove_dict):
    tweets_ints, encoded_labels = [],[]
    for i in range(len(data_set)):
        tweet = data_set['tweet'][i]
        label = data_set['label'][i]
        if(type(tweet) != str):
            continue
        idxs = [glove_dict.stoi[w]        # lookup the index of word
            for w in tweet.split()
            if w in glove_dict.stoi] # keep words that has an embedding
        if not idxs: # ignore tweets without any word with an embedding
            continue
        tweets_ints.append(idxs)
        encoded_labels.append(label)
    return tweets_ints, encoded_labels

In [0]:
tweets_ints, encoded_labels = data_set_to_glove_index(glove)

In [14]:
from collections import Counter
# outlier review stats
tweets_lens = Counter([len(x) for x in tweets_ints])
print("Zero-length tweets: {}".format(tweets_lens[0]))
print("Maximum tweet length: {}".format(max(tweets_lens)))

Zero-length tweets: 0
Maximum tweet length: 62


In [0]:
def pad_features(tweets_ints, seq_length):
    ''' Return features of review_ints, where each review is padded with 0's 
        or truncated to the input seq_length.
    '''
    
    # getting the correct rows x cols shape
    features = np.zeros((len(tweets_ints), seq_length), dtype=int)

    # for each review, I grab that review and 
    for i, row in enumerate(tweets_ints):
        features[i, -len(row):] = np.array(row)[:seq_length]
    
    return features

In [0]:
seq_length = max(tweets_lens)

features = pad_features(tweets_ints, seq_length=seq_length)
encoded_labels = np.array(encoded_labels)

In [17]:
print(features[:30,])

[[    0     0     0 ...    85    53  2706]
 [    0     0     0 ...   221  9193 50306]
 [    0     0     0 ...   316   226   325]
 ...
 [    0     0     0 ...    13  1863   328]
 [    0     0     0 ... 58381  1465     1]
 [    0     0     0 ...  1104    96  4799]]


### Train, Validation, Test Split

In [0]:
from sklearn.utils import shuffle
features, encoded_labels = shuffle(features, encoded_labels)

In [19]:
split_frac = 0.8

## split data into training, validation, and test data (features and labels, x and y)

split_idx = int(len(features)*split_frac)
train_x, remaining_x = features[:split_idx], features[split_idx:]
train_y, remaining_y = encoded_labels[:split_idx], encoded_labels[split_idx:]

test_idx = int(len(remaining_x)*0.5)
val_x, test_x = remaining_x[:test_idx], remaining_x[test_idx:]
val_y, test_y = remaining_y[:test_idx], remaining_y[test_idx:]

## print out the shapes of your resultant feature data
print("\t\t\tFeature Shapes:")
print("Train set: \t\t{}".format(train_x.shape), 
      "\nValidation set: \t{}".format(val_x.shape),
      "\nTest set: \t\t{}".format(test_x.shape))

			Feature Shapes:
Train set: 		(128920, 62) 
Validation set: 	(16115, 62) 
Test set: 		(16115, 62)


### DataLoader and Batching

In [0]:
from torch.utils.data import TensorDataset, DataLoader

# create Tensor datasets
train_data = TensorDataset(torch.from_numpy(train_x), torch.from_numpy(train_y))
valid_data = TensorDataset(torch.from_numpy(val_x), torch.from_numpy(val_y))
test_data = TensorDataset(torch.from_numpy(test_x), torch.from_numpy(test_y))

# dataloaders
batch_size = 50

# make sure the SHUFFLE your training data
train_loader = DataLoader(train_data, shuffle=True, batch_size=batch_size,drop_last=True)
valid_loader = DataLoader(valid_data, shuffle=True, batch_size=batch_size,drop_last=True)
test_loader = DataLoader(test_data, shuffle=True, batch_size=batch_size,drop_last=True)

In [21]:
len(train_loader)

2578

### Building the model

In [0]:
class TweetLSTM(nn.Module):
    def __init__(self, input_size, hidden_size, num_classes):
        super(TweetLSTM, self).__init__()
        self.emb = nn.Embedding.from_pretrained(glove.vectors)
        self.hidden_size = hidden_size
        self.rnn = nn.LSTM(input_size, hidden_size, batch_first=True)
        self.fc = nn.Linear(hidden_size, num_classes)
    
    def forward(self, x):
        # Look up the embedding
        x = self.emb(x)
        # Set an initial hidden state and cell state
        h0 = torch.zeros(1, x.size(0), self.hidden_size)
        c0 = torch.zeros(1, x.size(0), self.hidden_size)
        # Forward propagate the LSTM
        out, _ = self.rnn(x, (h0, c0))
        # Pass the output of the last time step to the classifier
        out = self.fc(out[:, -1, :])
        return out
num_classes = 6
model = TweetLSTM(input_size=50, hidden_size=50, num_classes=num_classes)

In [26]:
def get_accuracy(model, data_loader):
    correct, total = 0, 0
    for tweets, labels in data_loader:
        output = model(tweets)
        pred = output.max(1, keepdim=True)[1]
        correct += pred.eq(labels.view_as(pred)).sum().item()
        total += labels.shape[0]
    return float(correct) / float(total)

get_accuracy(model, test_loader)


0.30006211180124226

In [0]:
def train_rnn_network(model, train, valid, num_epochs=5, learning_rate=1e-5):
    criterion = nn.CrossEntropyLoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
    losses, train_acc, valid_acc = [], [], []
    epochs = []
    counter = 0
    for epoch in range(num_epochs):
        for tweets, labels in train:
            counter += 1
            optimizer.zero_grad()
            pred = model(tweets)
            loss = criterion(pred, labels)
            loss.backward()
            optimizer.step()
            if counter % 100 == 0:
              print("Step %d of Epoch: %d; Loss %f " % ( counter/100 ,epoch+1,float(loss)))
                
        losses.append(float(loss))

        epochs.append(epoch)
        train_acc.append(get_accuracy(model, train_loader))
        valid_acc.append(get_accuracy(model, valid_loader))
        print("Final Result for Epoch %d; Loss %f; Train Acc %f; Val Acc %f" % (
              epoch+1, loss, train_acc[-1], valid_acc[-1]))
        
    # plotting
    plt.title("Training Curve")
    plt.plot(losses, label="Train")
    plt.xlabel("Epoch")
    plt.ylabel("Loss")
    plt.show()

    plt.title("Training Curve")
    plt.plot(epochs, train_acc, label="Train")
    plt.plot(epochs, valid_acc, label="Validation")
    plt.xlabel("Epoch")
    plt.ylabel("Accuracy")
    plt.legend(loc='best')
    plt.show()

In [25]:
model_lstm = TweetLSTM(input_size=50, hidden_size=50, num_classes=num_classes)
train_rnn_network(model, train_loader, valid_loader, num_epochs=100, learning_rate=1e-3)
get_accuracy(model, test_loader)

Step 1 of Epoch: 1; Loss 1.715364 
Step 2 of Epoch: 1; Loss 1.720793 
Step 3 of Epoch: 1; Loss 1.696173 
Step 4 of Epoch: 1; Loss 1.804846 
Step 5 of Epoch: 1; Loss 1.570959 
Step 6 of Epoch: 1; Loss 1.712306 
Step 7 of Epoch: 1; Loss 1.598416 
Step 8 of Epoch: 1; Loss 1.623860 


KeyboardInterrupt: ignored

### Saving the model

In [0]:
#torch.save(model.state_dict(), 'checkpoint.pth')

### Loading the model

In [0]:
state_dict = torch.load('checkpoint.pth')

In [0]:
model.load_state_dict(state_dict)

### Inference

In [0]:
# Tweet Test
happy_tweet = 'Im happy'
sad_tweet = 'Im sad'
angry = 'Im angry'
surprised_tweet = 'Im surprised'
disgusted_tweet = 'Im disgusted'
afraid_tweet = 'Im afraid'

In [0]:
def tweet_to_glove_index(tweet,glove_dict):
    tweets_ints = []
    tweet = tweet.lower()
    idxs = [glove_dict.stoi[w]        # lookup the index of word
            for w in tweet.split()
            if w in glove_dict.stoi] # keep words that has an embedding
    tweets_ints.append(idxs)
    return tweets_ints

In [0]:
int_to_emotion = {0:'Happy', 1:'Sad' , 2:'Angry', 3:'Surprised', 4:'Disgusted', 5:'Afraid'}

def predict(model, test_tweet, sequence_length=max(tweets_lens)):
    
    
    # tokenize tweet
    test_ints = tweet_to_glove_index(test_tweet,glove)
    
    # pad tokenized sequence
    seq_length=sequence_length
    features = pad_features(test_ints, seq_length)
    
    # convert to tensor to pass into your model
    feature_tensor = torch.from_numpy(features)
    
    batch_size = feature_tensor.size(0)
    
    
    # get the output from the model
    output = model(feature_tensor)
    
    # convert output probabilities to predicted class (0 or 1)
    output_prob = nn.functional.softmax(output,dim=1)
    top_n_pred = output_prob.topk(3,dim=1) ## top 3 preds
    top_n_pred_prob, top_n_pred_index = top_n_pred[0].detach().numpy()[0], top_n_pred[1].detach().numpy()[0]
    print(test_tweet)
    print('Prediction:')
    for prob,index in zip(top_n_pred_prob,top_n_pred_index):
      print(int_to_emotion[index] , 'with' , str(int(prob*100))+"%", 'confidence')
    print('---------------')

In [48]:
predict(model,happy_tweet)
predict(model,sad_tweet)
predict(model,angry)
predict(model,surprised_tweet)
predict(model,disgusted_tweet)
predict(model,afraid_tweet)

Im happy
Prediction:
Happy with 46% confidence
Surprised with 24% confidence
Afraid with 12% confidence
---------------
Im sad
Prediction:
Sad with 82% confidence
Disgusted with 5% confidence
Happy with 5% confidence
---------------
Im angry
Prediction:
Disgusted with 34% confidence
Angry with 32% confidence
Happy with 10% confidence
---------------
Im surprised
Prediction:
Happy with 68% confidence
Sad with 8% confidence
Disgusted with 8% confidence
---------------
Im disgusted
Prediction:
Disgusted with 30% confidence
Angry with 25% confidence
Sad with 21% confidence
---------------
Im afraid
Prediction:
Surprised with 27% confidence
Sad with 23% confidence
Afraid with 22% confidence
---------------


In [0]:
tweets = ['he said he will be there and he showed up','']

In [63]:
for tweet in tweets:
  predict(model, tweet)

he said he will be there and he showed up
Prediction:
Happy with 32% confidence
Surprised with 20% confidence
Sad with 17% confidence
---------------
he said he will be there but he did not show up
Prediction:
Sad with 29% confidence
Surprised with 19% confidence
Disgusted with 18% confidence
---------------
he said he will be there and he showed up with his friends
Prediction:
Surprised with 24% confidence
Happy with 20% confidence
Sad with 16% confidence
---------------
